name: DirectorySync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DirectorySync:
    uses: EncoreDigitalGroup/.github/.github/workflows/directory-sync.yml@main
    with:
      source: 'guides/'
      targetRepo: 'encoredigitalgroup/internal-kb'
      targetDirectory: 'style-guide'
      commitMessage: '[Automated] DirectorySync'
    secrets:
      token: ${{ secrets.GH_GENERAL_ACCESS_TOKEN }}
