name: DirectorySync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DirectorySync:
    uses: EncoreDigitalGroup/.github/.github/workflows/directorySync.yml@latest
    with:
      source: 'guides/'
      targetRepo: 'encoredigitalgroup/internal-kb'
      targetDirectory: 'style-guide'
    secrets:
      token: ${{ secrets.GH_GENERAL_ACCESS_TOKEN }}
