name: DirectorySync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DirectorySync:
    uses: EncoreDigitalGroup/.github/.github/workflows/directorySync.yml@v1
    with:
      source: 'guides/'
      targetRepo: 'encoredigitalgroup/internal-kb'
      targetDirectory: 'StyleGuide'
    secrets:
      token: ${{ secrets.GH_GENERAL_ACCESS_TOKEN }}
